### ISSUE TITLE
wallet refactor bug

### ISSUE THREAD

**Issue by i-am-xhy** [Skynet2-0/Skynet2.0#42] opened 2016-05-27 13:28 UTC
the recent refactor left a bug in wallet for ommited self in __ignore_pasword_prompt

**Comment by i-am-xhy** [comment] 2016-05-31 07:24
fixed in most recent version of prototype2, will close issue once that branch is in master

**Comment by StefanBoodt** [comment] 2016-05-31 14:18
It was already fixed in #43 as stated before. I was assigned this as well. The way you close issues is by writing fixes/solves #issuenumber. Then the issue closes when the commit reaches master. This way you get a nice history of bugs and problems, and it is clear to development teams how and where the issue is fixed. This prevents redundant fixes when the issue reappears.

**Closed** 2016-06-01 09:56 UTC
Labels: bug
